name: Push Events only for Main Branch
on: 
  push:
    branches:
      - main 
  jobs:
    show-info:
      runs-on: ubuntu-latest
      steps: 
      - name: info
          run:|
            echo "this is a push event only when main branch is triggered"
      
