name: Scheduled Workflow
on: 
  schedule:
    - cron: '*/5 * * * *'   #run every 5 minutes
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: info
        run: |
          echo "this is scheduled task running every 5 minutes"
        
